debug: true
server:
  port:
    error:
      include-message: always
spring:
  sql:
  #    init:
  #      mode: always
  #      platform: postgresql
  output:
    ansi:
      enabled: always
  #
  # Add standalone postgres datasource config here
  #
  datasource:
    driver-class-name:
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/xpqdbqji
    username: xpqdbqji
    password: txnNDl8fWcRsIoHkQLM1EiwTe8KilTNK
  #
  # Add the appropriate JPA config here
  #
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
        ddl-auto: update
    generate-ddl: true
#        defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR